"""
Generate vocab.h for esp32-ai firmware from MiniMind's BPE+ByteLevel tokenizer.

对齐 src/gen_assets.py 的 VOCAB_BLOB/VOCAB_OFF 格式, 但关键改进:
  - 用 bytes_to_unicode 的逆映射还原每个 token 的【原始字节】(而非 tok.decode([i]))
    tok.decode([i]) 对 ByteLevel 中间片段会输出 U+FFFD 替换符, 污染字节流;
    原始字节片段在连续 token 拼合后才是正确的 UTF-8 文本 (串口侧逐 token 写入会正确拼合)。
  - 特殊 token (id 0-35): decode 为空或为标记文本, 均按原始字节保留 (生成时会被停止条件拦截, 不会输出)

用法:
    python scripts/gen_vocab_minimind.py
    python scripts/gen_vocab_minimind.py --out D:/codes/esp32-ai/firmware/esp32_llm_zh_v3/vocab.h
"""

import argparse
import json
import os
import sys

sys.stdout.reconfigure(encoding='utf-8')
from tokenizers import Tokenizer

PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def build_byte_map():
    """bytes_to_unicode 的逆映射: unicode char -> original byte (HF ByteLevel)."""
    bs = list(range(ord('!'), ord('~') + 1)) + list(range(ord('¡'), ord('¬') + 1)) + list(range(ord('®'), ord('ÿ') + 1))
    cs = bs[:]
    n = 0
    for b in range(2 ** 8):
        if b not in bs:
            bs.append(b)
            cs.append(2 ** 8 + n)
            n += 1
    return {chr(c): b for b, c in zip(bs, cs)}


def token_raw_bytes(tok_str, c2b):
    """将 ByteLevel 映射后的 token 字符串还原为原始字节."""
    return bytes(c2b.get(ch, ord(ch)) for ch in tok_str)


def main():
    ap = argparse.ArgumentParser(description='Generate MiniMind BPE vocab.h for esp32-ai')
    ap.add_argument('--tokenizer', default=os.path.join(PROJECT_ROOT, 'model', 'tokenizer.json'))
    ap.add_argument('--out', default=os.path.join(PROJECT_ROOT, '..', 'esp32-ai', 'firmware', 'esp32_llm_zh_v3', 'vocab.h'))
    ap.add_argument('--vocab-n', type=int, default=6400, help='vocab.h 的 VOCAB_N (固件与 model.bin header 需一致)')
    args = ap.parse_args()

    # 1. 从 tokenizer.json 读取原始 vocab (token -> id), 保证与模型训练完全一致
    with open(args.tokenizer, 'r', encoding='utf-8') as f:
        tj = json.load(f)
    vocab = tj['model']['vocab']
    itos = {v: k for k, v in vocab.items()}
    c2b = build_byte_map()
    V = args.vocab_n
    assert V == len(itos), f'VOCAB_N {V} != tokenizer vocab {len(itos)}'

    # 2. 逐 token 还原原始字节 (与训练时字节完全一致)
    blob = bytearray()
    offs = [0]
    empty_ids = []
    for i in range(V):
        tok_str = itos.get(i, '')
        b = token_raw_bytes(tok_str, c2b)
        if not b:
            empty_ids.append(i)
            blob.append(0)  # 空 token -> 单个 NUL, 保持 offsets 对齐
        else:
            blob.extend(b)
        offs.append(len(blob))

    # 3. 写 C header
    os.makedirs(os.path.dirname(args.out), exist_ok=True)
    with open(args.out, 'w', encoding='utf-8') as f:
        f.write('// Generated by minimind/scripts/gen_vocab_minimind.py -- MiniMind BPE token id -> raw UTF-8 bytes.\n')
        f.write('#ifndef VOCAB_H\n#define VOCAB_H\n')
        f.write(f'#define VOCAB_N {V}\n')
        f.write(f'static const unsigned char VOCAB_BLOB[{len(blob)}] = {{\n')
        for i in range(0, len(blob), 20):
            f.write('  ' + ','.join(str(b) for b in blob[i:i + 20]) + ',\n')
        f.write('};\n')
        f.write(f'static const int VOCAB_OFF[{len(offs)}] = {{\n')
        for i in range(0, len(offs), 20):
            f.write('  ' + ','.join(str(o) for o in offs[i:i + 20]) + ',\n')
        f.write('};\n#endif\n')

    print(f'wrote {args.out}: {V} tokens, blob {len(blob) / 1024:.1f} KB')
    print(f'empty tokens: {len(empty_ids)} (id {empty_ids[:10]}...)')

    # 4. 往返验证: 常用中文词条
    print('\n=== 往返验证 (字节拼合) ===')
    for text, ids in [('你好', [1968]), ('什么是机器学习', [1403, 357, 2683]), ('如何缓解工作压力', [1185, 6354, 1159, 2713])]:
        parts = [bytes(blob[offs[t]:offs[t + 1]]) for t in ids]
        joined = b''.join(parts)
        print(f'{text!r} <- ids {ids} -> bytes {joined} -> {joined.decode("utf-8", errors="replace")!r}')


if __name__ == '__main__':
    main()
